name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow for version tags like v1.0.0

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            goos: linux
            goarch: amd64
          - os: macos-latest
            platform: darwin
            goos: darwin
            goarch: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        id: set_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/beacon-${{ matrix.platform }}-amd64 ./cmd/cli/beacon/beacon.go
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/install-${{ matrix.platform }}-amd64 ./cmd/cli/install/install.go

      - name: Create release
        if: env.TAG_EXISTS == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload beacon binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/beacon-${{ matrix.platform }}-amd64
          asset_name: beacon-${{ env.VERSION }}-${{ matrix.platform }}-amd64
          asset_content_type: application/octet-stream

      - name: Upload install binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/install-${{ matrix.platform }}-amd64
          asset_name: install-${{ env.VERSION }}-${{ matrix.platform }}-amd64
          asset_content_type: application/octet-stream