name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            platform: linux
            goos: linux
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/beacon-${{ matrix.platform }}-${{ matrix.goarch }} ./cmd/cli/beacon/beacon.go
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./bin/install-${{ matrix.platform }}-${{ matrix.goarch }} ./cmd/cli/install/install.go

      - name: Delete existing tag and release (if exists)
        run: |
          TAG=${{ github.ref_name }}
          echo "Checking if release $TAG exists..."
          if gh release view "$TAG" &>/dev/null; then
            echo "Release $TAG exists. Deleting..."
            gh release delete "$TAG" --yes || echo "Failed to delete release."
            git push --delete origin "$TAG" || echo "Failed to delete tag."
          else
            echo "No existing release for $TAG."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        run: gh release create ${{ github.ref_name }} ./bin/* --title "Release ${{ github.ref_name }}" --notes "Automated release for ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}